name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: runner

      - run: |
          echo $(cat generated.txt)

      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          date > generated.txt
          git checkout -b runner
          git add .
          git commit -m "generated"
          git push origin -d runner
          git push -u
