name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: runner

      - run: |
          cat generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config pull.rebase false
          git pull origin main
          date > generated.txt
          git checkout runner
          git add .
          git commit -m "generated"
          git push
